# Generated by Django 5.0.3 on 2024-03-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.workexperience'),
        ),
    ]
