# Generated by Django 5.0.3 on 2024-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, to='employee.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='employee.qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.ManyToManyField(blank=True, to='employee.workexperience'),
        ),
    ]
