# Generated by Django 5.0.3 on 2024-03-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_address_details_employee_addressdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='addressDetails',
            new_name='address_details',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phoneNo',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='workExperience',
            new_name='work_experience',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='fromDate',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='qualificationName',
            new_name='qualification_name',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='toDate',
            new_name='to_date',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='fromDate',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='toDate',
            new_name='to_date',
        ),
    ]
